# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetwin.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(450, 420)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 451, 421))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.treeWidget = QtGui.QTreeWidget(self.tab)
        self.treeWidget.setGeometry(QtCore.QRect(10, 30, 256, 291))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.btnOk = QtGui.QPushButton(self.tab)
        self.btnOk.setGeometry(QtCore.QRect(300, 360, 75, 23))
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.btnCancel = QtGui.QPushButton(self.tab)
        self.btnCancel.setGeometry(QtCore.QRect(200, 360, 75, 23))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.labMonth = QtGui.QLabel(self.tab)
        self.labMonth.setGeometry(QtCore.QRect(330, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.labMonth.setFont(font)
        self.labMonth.setText(_fromUtf8(""))
        self.labMonth.setObjectName(_fromUtf8("labMonth"))
        self.labMonth_3 = QtGui.QLabel(self.tab)
        self.labMonth_3.setGeometry(QtCore.QRect(310, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setUnderline(True)
        self.labMonth_3.setFont(font)
        self.labMonth_3.setObjectName(_fromUtf8("labMonth_3"))
        self.labDay = QtGui.QLabel(self.tab)
        self.labDay.setGeometry(QtCore.QRect(310, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.labDay.setFont(font)
        self.labDay.setText(_fromUtf8(""))
        self.labDay.setObjectName(_fromUtf8("labDay"))
        self.labMonth_2 = QtGui.QLabel(self.tab)
        self.labMonth_2.setGeometry(QtCore.QRect(270, 110, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.labMonth_2.setFont(font)
        self.labMonth_2.setObjectName(_fromUtf8("labMonth_2"))
        self.labDay_2 = QtGui.QLabel(self.tab)
        self.labDay_2.setGeometry(QtCore.QRect(270, 150, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.labDay_2.setFont(font)
        self.labDay_2.setObjectName(_fromUtf8("labDay_2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(30, 80, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.sliderFrom = QtGui.QSlider(self.tab_2)
        self.sliderFrom.setGeometry(QtCore.QRect(30, 120, 331, 22))
        self.sliderFrom.setMaximum(365)
        self.sliderFrom.setOrientation(QtCore.Qt.Horizontal)
        self.sliderFrom.setObjectName(_fromUtf8("sliderFrom"))
        self.labFrom = QtGui.QLabel(self.tab_2)
        self.labFrom.setGeometry(QtCore.QRect(160, 80, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.labFrom.setFont(font)
        self.labFrom.setObjectName(_fromUtf8("labFrom"))
        self.labTo = QtGui.QLabel(self.tab_2)
        self.labTo.setGeometry(QtCore.QRect(160, 200, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.labTo.setFont(font)
        self.labTo.setObjectName(_fromUtf8("labTo"))
        self.sliderTo = QtGui.QSlider(self.tab_2)
        self.sliderTo.setGeometry(QtCore.QRect(30, 230, 331, 22))
        self.sliderTo.setMaximum(365)
        self.sliderTo.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTo.setObjectName(_fromUtf8("sliderTo"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(40, 200, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.btnOk2 = QtGui.QPushButton(self.tab_2)
        self.btnOk2.setGeometry(QtCore.QRect(300, 360, 75, 23))
        self.btnOk2.setDefault(True)
        self.btnOk2.setObjectName(_fromUtf8("btnOk2"))
        self.btnCancel2 = QtGui.QPushButton(self.tab_2)
        self.btnCancel2.setGeometry(QtCore.QRect(200, 360, 75, 23))
        self.btnCancel2.setObjectName(_fromUtf8("btnCancel2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.treeWidget.headerItem().setText(0, _translate("Form", "Range of dates", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "Months", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "January", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Form", "February", None))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Form", "March", None))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("Form", "April", None))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("Form", "May", None))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("Form", "June", None))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("Form", "July", None))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("Form", "August", None))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("Form", "September", None))
        self.treeWidget.topLevelItem(0).child(9).setText(0, _translate("Form", "October", None))
        self.treeWidget.topLevelItem(0).child(10).setText(0, _translate("Form", "November", None))
        self.treeWidget.topLevelItem(0).child(11).setText(0, _translate("Form", "December", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "Days", None))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Form", "1 - 7", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, _translate("Form", "1", None))
        self.treeWidget.topLevelItem(1).child(0).child(1).setText(0, _translate("Form", "2", None))
        self.treeWidget.topLevelItem(1).child(0).child(2).setText(0, _translate("Form", "3", None))
        self.treeWidget.topLevelItem(1).child(0).child(3).setText(0, _translate("Form", "4", None))
        self.treeWidget.topLevelItem(1).child(0).child(4).setText(0, _translate("Form", "5", None))
        self.treeWidget.topLevelItem(1).child(0).child(5).setText(0, _translate("Form", "6", None))
        self.treeWidget.topLevelItem(1).child(0).child(6).setText(0, _translate("Form", "7", None))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Form", "8 - 14", None))
        self.treeWidget.topLevelItem(1).child(1).child(0).setText(0, _translate("Form", "8", None))
        self.treeWidget.topLevelItem(1).child(1).child(1).setText(0, _translate("Form", "9", None))
        self.treeWidget.topLevelItem(1).child(1).child(2).setText(0, _translate("Form", "10", None))
        self.treeWidget.topLevelItem(1).child(1).child(3).setText(0, _translate("Form", "11", None))
        self.treeWidget.topLevelItem(1).child(1).child(4).setText(0, _translate("Form", "12", None))
        self.treeWidget.topLevelItem(1).child(1).child(5).setText(0, _translate("Form", "13", None))
        self.treeWidget.topLevelItem(1).child(1).child(6).setText(0, _translate("Form", "14", None))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Form", "15 - 21", None))
        self.treeWidget.topLevelItem(1).child(2).child(0).setText(0, _translate("Form", "15", None))
        self.treeWidget.topLevelItem(1).child(2).child(1).setText(0, _translate("Form", "16", None))
        self.treeWidget.topLevelItem(1).child(2).child(2).setText(0, _translate("Form", "17", None))
        self.treeWidget.topLevelItem(1).child(2).child(3).setText(0, _translate("Form", "18", None))
        self.treeWidget.topLevelItem(1).child(2).child(4).setText(0, _translate("Form", "19", None))
        self.treeWidget.topLevelItem(1).child(2).child(5).setText(0, _translate("Form", "20", None))
        self.treeWidget.topLevelItem(1).child(2).child(6).setText(0, _translate("Form", "21", None))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("Form", "22 - 31", None))
        self.treeWidget.topLevelItem(1).child(3).child(0).setText(0, _translate("Form", "22", None))
        self.treeWidget.topLevelItem(1).child(3).child(1).setText(0, _translate("Form", "23", None))
        self.treeWidget.topLevelItem(1).child(3).child(2).setText(0, _translate("Form", "24", None))
        self.treeWidget.topLevelItem(1).child(3).child(3).setText(0, _translate("Form", "25", None))
        self.treeWidget.topLevelItem(1).child(3).child(4).setText(0, _translate("Form", "26", None))
        self.treeWidget.topLevelItem(1).child(3).child(5).setText(0, _translate("Form", "27", None))
        self.treeWidget.topLevelItem(1).child(3).child(6).setText(0, _translate("Form", "28", None))
        self.treeWidget.topLevelItem(1).child(3).child(7).setText(0, _translate("Form", "29", None))
        self.treeWidget.topLevelItem(1).child(3).child(8).setText(0, _translate("Form", "30", None))
        self.treeWidget.topLevelItem(1).child(3).child(9).setText(0, _translate("Form", "31", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.btnOk.setText(_translate("Form", "OK", None))
        self.btnCancel.setText(_translate("Form", "Cancel", None))
        self.btnCancel.setShortcut(_translate("Form", "Alt+C", None))
        self.labMonth_3.setText(_translate("Form", "Filter", None))
        self.labMonth_2.setText(_translate("Form", "Month:", None))
        self.labDay_2.setText(_translate("Form", "Day:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Filter by Month/Day", None))
        self.label.setText(_translate("Form", "Filter from:", None))
        self.labFrom.setText(_translate("Form", "2014-01-01", None))
        self.labTo.setText(_translate("Form", "2014-12-31", None))
        self.label_2.setText(_translate("Form", "Filter to:", None))
        self.btnOk2.setText(_translate("Form", "OK", None))
        self.btnCancel2.setText(_translate("Form", "Cancel", None))
        self.btnCancel2.setShortcut(_translate("Form", "Alt+C", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Filter by Range", None))

